export const FETCH = 'jobs/FETCH'
export const MERGE = 'jobs/MERGE'
export const NEW = 'jobs/NEW'
export const UPDATE = 'jobs/UPDATE'
export const LOADING = 'jobs/LOADING'
export const ADD_TOUCH = 'jobs/ADD_TOUCH'
export const CHANGE_SORT = 'jobs/CHANGE_SORT'
