runtime: nodejs
env: flex

env_variables:
  JWT_SECRET: 'f66c77c400a7eb09caf7ab694b936f039d6fae43605490563881a843804d4f73'
  SQL_USER: 'prod'
  SQL_PASSWORD: 'prod'
  SQL_DATABASE: 'jobby_prod'
  INSTANCE_CONNECTION_NAME: 'jobby-job-search:us-east1:jobby-job-search'

beta_settings:
  cloud_sql_instances: 'jobby-job-search:us-east1:jobby-job-search'

skip_files:
 - ^node_modules$
