export const FETCH = 'contacts/FETCH'
export const NEW = 'contacts/NEW'
export const UPDATE = 'contacts/UPDATE'
export const LOADING = 'contacts/LOADING'
export const ADD_TOUCH = 'contacts/ADD_TOUCH'
