export const FETCH = 'companies/FETCH'
export const MERGE = 'companies/MERGE'
export const NEW = 'companies/NEW'
export const UPDATE = 'companies/UPDATE'
export const LOADING = 'companies/LOADING'
export const REMOVE_JOB = 'companies/REMOVE_JOB'
export const ADD_JOB = 'companies/ADD_JOB'
